### PR TITLE
[issue #15, issue #12]

### PR DESCRIPTION
**Pull request by realsoftdev**
- Completed https://github.com/opentaps/opentaps_seas/issues/15
- Completed https://github.com/opentaps/opentaps_seas/issues/12

### CODE REVIEW

**Comment by rybalko** [comment]
"Implement tests for importing tags from csv #15" looks good for me.
but about "Add test for verifying bacnet configs are stored as tags on importing #12"
several fields are missed in the test:
bacnet.csv
Property,Writable,Index,Notes
and
bacnet.config
device_id
registry_config
interval
device_id and interval are important
also there is no verification that prefix + "/" + bacnet_reference_point_name is set to topic,
and interval should be set to "interval" tag

**Comment by rybalko** [comment]
"Implement tests for importing tags from csv #15" looks good for me.
but about "Add test for verifying bacnet configs are stored as tags on importing #12"
several fields are missed in the test:
bacnet.csv
Property,Writable,Index,Notes
and
bacnet.config
device_id
registry_config
interval
device_id and interval are important
also there is no verification that prefix + "/" + bacnet_reference_point_name is set to topic,
and interval should be set to "interval" tag

**Comment by realsoftdev** [comment]
Regarding missing fields
Those fields are same functionality with other fields so I thought we need to test with some fields.

**Comment by rybalko** [comment]
Property,Writable,Index,Notes
shoud be set because we expect fixed csv structure
device_id
registry_config
interval
are importand because they are used in the export
also interval is specific, because it should be set to "interval" field instead of bacnet_interval
and we should be sure topic =  prefix + "/" + bacnet_reference_point_name

**Comment by realsoftdev** [comment]
okay

**Pull request merged**
